#!/bin/zsh

DIR="resumes"
COMMON_OPTIONS=(
    --variable documentclass:article
    --variable geometry:margin=3cm
    --variable geometry:top=1cm
    --variable pagesize:a4
    --variable fontsize:10pt
    --variable linestretch:1.25
    --variable pagestyle:plain
    --variable urlcolor:Blue3
    --variable urlstyle:rm
    # --variable indent
)

# english
pandoc -o $DIR/resume.pdf $DIR/resume.md "${COMMON_OPTIONS[@]}"

# korean
pandoc -o $DIR/resume-kr.pdf $DIR/resume-kr.md "${COMMON_OPTIONS[@]}" --pdf-engine=xelatex --variable mainfont='Nanum Myeongjo'

# integrated
pdftk $DIR/resume.pdf $DIR/resume-kr.pdf cat output $DIR/resume-all.pdf
